WebCalculadora/Controllers/User/CreateStockController.cs
using Microsoft.AspNetCore.Mvc;
using WebCalculadora.Models;
using WebCalculadora.Services;
using WebCalculadora.Tools;

namespace WebCalculadora.Controllers.User
{
    public class CreateStockController : Controller
    {
        [BindProperty]
        public PlanillaCabecera? cabecera { get; set;}
        public IActionResult Index()
        {
            return View();
        }

        public ActionResult N_inputs()
        {
            ViewData["count"] = cabecera.Count;

            return View("Index");
        }
        public async Task<ActionResult> N_inputsValues()
        {
            DecodedToken decoded = new DecodedToken();

            cabecera.User_id = decoded.Decoded(Request.Cookies["Token"]);

            PlanillaCabeceraBD service = new PlanillaCabeceraBD();

            int result = await service.POSTAsync(cabecera);

            if(result == 1)
            {
                return RedirectToAction("Index", "Planillas");
            }            
            return Json(cabecera.Campos_Json);
        }
    }    
}

WebCalculadora/Controllers/User/MenuController.cs
using Microsoft.AspNetCore.Mvc;
using WebCalculadora.Services;
using WebCalculadora.Models;
namespace WebCalculadora.Controllers.User
{
    public class MenuController : Controller
    {
        Models.User user = new Models.User();

        UserStockBD UserStockService = new UserStockBD();

        [BindProperty]
        public UserStock UserStock { get; set; }
     
        public IActionResult Index()
        {
            if (Request.Cookies["Token"] != null)                           
                return View();            
            return RedirectToAction("Index", "Login");
        }
        
        public async Task<ActionResult> MenuStock()
        {
            if (Request.Cookies["Token"] != null)
            {
                user.User_id = Get_idSesionUser();

                ViewData["StockUser"] = await UserStockService.Get_stock(user);//consulta a servico sobre stock

                return View(UserStock);
            }

            return RedirectToAction("Index", "Login");
        }

        public ActionResult CreateStock()
        {            
            return View();
        }

        public async Task<ActionResult> GuardarRegistro()
        {
            if (ModelState.IsValid)
            {
                Reply oR = new Reply();
                UserStock.User_id = Get_idSesionUser();
                oR = await UserStockService.SetStockAsync(UserStock);
            }

            return RedirectToAction("MenuStock");
        }

        public async Task<ActionResult> EliminarRegistro(int id)
        {
            Reply oR = new Reply();

            oR = await UserStockService.Delete(id);

            if(oR.result != 0)
            {
                return RedirectToAction("MenuStock");
            }
           
            return View();
        }
        public async Task<ActionResult> ModificarStock(int id)
        {
            UserStock = await UserStockService.ReadIdAsync(id);
            return View(UserStock);
        }
        public async Task<ActionResult> SetModificacion()
        {
            Reply oR = new Reply();

            oR = await UserStockService.ModifyStock(UserStock);

            return RedirectToAction("MenuStock");
        }
        public ActionResult Logout()
        {            
            if(Request.Cookies["Token"] != null)
            {
                Response.Cookies.Delete("Token");

                return RedirectToAction("Index", "Login");
            }
            return RedirectToAction("Index", "Login");
        }
        public int Get_idSesionUser()
        {
            var token = Request.Cookies["Token"];//guardo cookies

            Models.User user = new Models.User();//creo modelo donde se almacenara mi id

            Tools.DecodedToken decoded = new Tools.DecodedToken();//decodificador de tokens

            return (int)(user.User_id = decoded.Decoded(token.ToString()));
        }
    }
}

WebCalculadora/Views/Menu/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebCalculadora.styles.css" asp-append-version="true" />

    <style>
        #button_accept a
        {
            display: inline-block;
            background-color: #10263c;
            padding: 10px;
            border: 2px solid #b00202;
            text-decoration: none;
            font-weight: bold;
            color: #b00202;
            transition-duration: 0.4s;
            cursor: pointer;
            margin: 2px 2px;
        }
        #button_accept a:hover
        {
            background-color: #ff9933;
        }
       body
       {
           background-color: #10263c;
       }
       #Titulo
       {
           text-align:center;
           font-family:Lucida Console;
       }
        .imagen
        {
            height: 30%;
            background-image: url("https://i.pinimg.com/originals/b2/2a/a2/b22aa22b2f3f55b6468361158d52e2e7.gif");
            background-repeat:no-repeat;
            background-position-x:center;
            background-position-y:center;
            background-size: 50rem;
            padding: 200px;
        } 
    </style>
</head>

<body>
    
    
        <div class ="col">
            <div class ="row">
                <form asp-controller="CreateStock" asp-action="Index">
                    <div style="text-align:center; margin-top:5%;">
                        <h1 style="font-family:Lucida Console; color:White">Gracias por formar parte</h1>

                        <h4 style="font-family:Lucida Console; color:White">Este proyecto esta destinado a la creacion y manipulacion de datos</h4>

                        <div class="imagen">              
                               
                        </div>  
                          <p style="color:White;">Dale click a continuar para manipular tus tablas</p>

                           <div id = button_accept>
                              <a asp-action="Index" asp-controller="CreateStock">ACEPTAR</a>
                           </div>
                    </div>             
                </form>   
            </div>
        </div>             
    

</body>

<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Menu - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
</footer>
</html>

WebCalculadora/Views/Menu/MenuStock.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = null;
    List<UserStock> stock = (List<UserStock>)ViewData["StockUser"];
    int indice = stock.Count;    
}
@model UserStock
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebCalculadora.styles.css" asp-append-version="true" />

    @section Scripts
     {
        <partial name="_ValidationScriptsPartial" />
     }

    <style>
        
        body 
        {
            margin:0;
            background: #232526;                                                /* fallback for old browsers */
            background: -webkit-linear-gradient(to right, #414345, #232526);  /* Chrome 10-25, Safari 5.1-6 */
            background: linear-gradient(to right, #414345, #232526);            /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */         
        }
        
        ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            overflow: hidden;
            background-color: #333;
            position: fixed;
            top: 0;
            width: 100%;
        }
        
        .navegate_items
        {
             float: left;
        }
        .navegate_items a
        {
            display: block;
            color: white;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }
        
        .navegate_items:hover:not(.active) 
        {
            background-color:#669999;
            color:black;
        }
        #customers 
        {
          font-family: Arial, Helvetica, sans-serif;
          border-collapse: collapse;
          width: 100%;
          background-color:#2dd2d2;
        }
        
        #customers td, #customers th 
        {
          border: 1px solid #ddd;
          padding: 8px;
        }               
        
        #customers tr:hover {background-color: #ddd; transition-duration: 0.50s;}
        
        #customers th 
        {
          padding-top: 12px;
          padding-bottom: 12px;
          text-align: left;
          background-color:#609f9f;
          color: #132020;
          font-size:smaller;
        }
        .Container_text_imput
        {
            
                        
        }
        #navegate_salir #salir
        {
            display: block;
            color: white;
            padding: 14px 16px;
            text-decoration: none;              
        }
        #navegate_salir:hover
        {            
             transition-duration: 1.50s;
             background-color:#be1e1e;
        }
        #navegate_salir_item li
        {
             float:right;
             transition-duration: 0.4s;
             cursor: pointer;

        }
        #container_stock
        {
            margin-left:70px;
            margin-top:90px;
        }
        .Container_text_imput h7
        {
            /*background-color:blueviolet;*/
            color:white;
        }
    </style>
</head>

<body>

    <ul class="fixed-top">
      <li class="navegate_items"><a asp-action = "MenuStock" >Tus Stocks</a></li>
      <li class="navegate_items"><a asp-controller = "CreateStock" asp-action= "Index" >Crear Stocks</a></li>
      <li class="navegate_items"><a asp-controller = "Planillas" asp-action= "Index" >Planillas</a></li>

      <div id="navegate_salir_item">
          <li id="navegate_salir"><a id="salir" asp-action="Logout">Salir</a></li>
      </div>      
    </ul>

    <div style="margin-top:70px; margin-left:70px;">
        <audio controls autoplay>
            <source src="/jinsang-feelings.mp3" type="audio/mp3"/>
        </audio>
    </div>       

    <div id="container_stock">
        <div class="col-11">
         <form asp-action = "GuardarRegistro" asp-controller="Menu" method="POST">
            <div class="Container_text_imput">        
                <h7>Nombre</h7>
                <span asp-validation-for="Nombre" class="text-danger"></span>
                <input class="form-control" asp-for="Nombre" type="text" />
                 <span asp-validation-for="Marca" class="text-danger"></span>
                <h7>Marca</h7>
                <input class="form-control" asp-for="Marca" type="text"/>
               <span asp-validation-for="Modelo" class="text-danger"></span>
                <h7>Modelo</h7>
                <input class="form-control" asp-for="Modelo" type="text"/>
                <span asp-validation-for="Tipo" class="text-danger"></span>
                 <h7>Tipo</h7>
                <input class="form-control" asp-for="Tipo" type="text"/>
                 <span asp-validation-for="Area" class="text-danger"></span>
                <h7>Area</h7>
                <input class="form-control" asp-for="Area" type="text"/>
                <span asp-validation-for="Cantidad" class="text-danger"></span>
                <h7>Cantidad</h7>
                <input class="form-control" asp-for="Cantidad" type="text"/>
                <span asp-validation-for="Estado" class="text-danger"></span>
                <h7>Estado</h7>
                 <input class="form-control" asp-for= "Estado" type="text"/>
                 
    
                 <div style="margin-top:20px; margin-left:45%;">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                </div>
            </div>
         </form>
        </div>
    </div>    

    <div style="padding:20px;margin-top:50px;height:1500px;">

        <table id="customers">
           <tr>
             <th>id</th>
             <th>Nombre</th>
             <th>Marca</th>
             <th>Modelo</th>
             <th>Tipo</th>
             <th>Area</th>
             <th>Cantidad</th>
             <th>Estado</th>
           </tr>

            @for(int i = 0; i<= indice -1; i++)
            {
                <tr>
                    <td>@stock[i].Id</td>
                    <td>@stock[i].Nombre</td>
                    <td>@stock[i].Marca</td>
                    <td>@stock[i].Modelo</td>
                    <td>@stock[i].Tipo</td>
                    <td>@stock[i].Area</td>
                    <td>@stock[i].Cantidad</td>
                    <td>@stock[i].Estado</td>
                    <td><a asp-action="ModificarStock" asp-controller="Menu" asp-route-id= "@stock[i].Id">Modificar</a></td>
                    <td><a asp-action="EliminarRegistro" asp-controller="Menu" asp-route-id= "@stock[i].Id">Eliminar</a></td>
                </tr>
            }
        </table>
    </div>

      <script src="~/lib/jquery/dist/jquery.min.js"></script>
      <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
      <script src="~/js/site.js" asp-append-version="true"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js"></script>
</body>

<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Menu - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
</footer>
</html>