WebCalculadora/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using WebCalculadora.Models;
using WebCalculadora.Services;
namespace WebCalculadora.Controllers
{
    public class LoginController : Controller
    {        
        [BindProperty]
        public UserLogin ModelUser { get; set; }
        public IActionResult Index()
        {
            if (Request.Cookies["Token"] != null)
            {
                return RedirectToAction("Index", "Menu");
            }

            return View();
        }  
        public async Task<ActionResult> LoginUser()
        {
            Reply? oR = new Reply();

            if (ModelState.IsValid)
            {
                Auth auth = new Auth(); 
                oR = await auth.AuthUser(ModelUser); //verify password and generate token 

                if(oR.result > 0)
                {
                    SetCookie(oR.data.ToString());                                        

                    return RedirectToAction("Index", "Menu");
                }
                else
                {
                    if(oR.message == "")
                         ModelState.AddModelError("Email1","El correo o la contraseña son incorrectos");
                    else
                         ModelState.AddModelError("Email1", oR.message);
                    return View("Index");
                }                
            }
            return Json(oR.message);
        }

        private void SetCookie(string token)
        {
            CookieOptions Options = new CookieOptions();
            Options.Expires = DateTime.Now.AddDays(2);
            Response.Cookies.Append("Token", token, Options);
        }
    }
}

WebCalculadora/Controllers/RegisterController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebCalculadora.Controllers
{
    public class RegisterController : Controller
    {
        DataBase.RegisterBD Register = new DataBase.RegisterBD();

        [BindProperty]
        public Models.UserRegister? UserRegister { get; set; }
        public IActionResult Index()
        {
            return View();
        }

        public async  Task<ActionResult> RegisterUser()
        {       
            if(ModelState.IsValid)
            {
                //si es valido, haceme el registro
                int result = await Register.PostUser(UserRegister);

                if(result == 200)
                {
                    //
                    return RedirectToAction("Index");
                }
                else
                {
                    return Json("??");
                }                      
            }
            else
            {
                return RedirectToAction("Index");
            }      
        }
    }
}

WebCalculadora/Views/Login/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
@model UserLogin

@section Scripts
{
<partial name="_ValidationScriptsPartial" />
}

    <head>
        <title>Login</title>
    </head>

    <body style="background:#ffdd90;">
        <div class= "container">
          <div class="row justify-content-center">
               <div class="col-4">
                <form asp-action = "LoginUser" asp-controller="Login" method="post">
              <div class="mb-2">
                     <label for="exampleInputEmail1" class="form-label">Email address</label>
                      <input class="form-control" asp-for="Email1" type="text">
                      <span asp-validation-for = "Email1" class="text-danger"></span>
              </div>

              <div class="mb-2">
                      <label for="exampleInputPassword1" class="form-label">Password</label>
                      <input class="form-control" asp-for="Password1" type="text">
                      <span asp-validation-for = "Password1" class="text-danger"></span>
              </div>

              <div class="mb- form-check">
                      <input type="checkbox" class="form-check-input" id="exampleCheck1">
                      <label class="form-check-label" for="exampleCheck1">Check me out</label>
              </div>

              <div class="row">
                  <div class="col-8">
                     <button type="submit" class="btn btn-primary">Login</button>
                  </div>
                     
                  <div class="col-4" style="margin-top: 10px">
                      <a style="margin-left: 45px;" asp-action="index" asp-controller="Register" >Registrate</a>
                  </div>  
              </div>                     
            </form>
           </div>
          </div>
        </div>
    </body>